# Generated by Django 3.2.11 on 2022-02-02 00:21

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 2, 0, 21, 27, 78375, tzinfo=utc), help_text='Fecha de creacion', verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de ultima modificacion', verbose_name='modified_at'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El formato deber ser: +5959******. Con un maximo de 15 digitos', regex='\\+?5?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(db_index=True, default=2979427, error_messages={'unique': 'Ya existe un usuario con esta credencial'}, help_text='User identification number', max_length=50, unique=True, verbose_name='user id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con este email.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
