# Generated by Django 3.2.11 on 2022-02-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeats', '0002_alter_heartbeat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat',
            old_name='velocity',
            new_name='speed',
        ),
    ]
